variables:
  CUSTOM_CI_BUILDS_DIR: "/usr/workspace/msr/gitlab-runner"
  BUILD_ROOT: ${CI_PROJECT_DIR}
  TARGET_BRANCH: ${CI_COMMIT_REF_NAME}

stages:
  - build

# Template for jobs triggering a build-and-test sub-pipelines:
.build:
  stage: build
  trigger:
    include:
      - local: '.gitlab/${CI_MACHINE}-build-and-test.yml'
    strategy: depend
    forward:
      pipeline_variables: true
    id_tokens:
      CI_JOB_JWT:
        aud: https://lc.llnl.gov/gitlab

include:
  - local: .gitlab/subscribed-pipelines.yml
  - project: 'lc-templates/id_tokens'
    file: 'id_tokens.yml'
