sudo: required

language: c

compiler:
    - gcc

install:
    # none

script:
    - which g++
    - g++ --version
    - make VERBOSE=1

before_script:
    - sudo apt-get install -y linux-headers-`uname -r`

notifications:
    email:
        recipients:
            - labasan1@llnl.gov
        on_success: always
        on_failure: always
