language: c

compiler:
    - gcc

install:
    # none

script:
    - uname -a
    - which g++
    - g++ --version
    - make VERBOSE=1

matrix:
    include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial

before_script:
    - sudo apt-get install -y linux-headers-`uname -r`

notifications:
    email:
        recipients:
            - labasan1@llnl.gov
        on_success: always
        on_failure: always
