.\" Copyright (c) 2016, Intel Corporation
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\"     * Redistributions of source code must retain the above copyright
.\"       notice, this list of conditions and the following disclaimer.
.\"
.\"     * Redistributions in binary form must reproduce the above copyright
.\"       notice, this list of conditions and the following disclaimer in
.\"       the documentation and/or other materials provided with the
.\"       distribution.
.\"
.\"     * Neither the name of Intel Corporation nor the names of its
.\"       contributors may be used to endorse or promote products derived
.\"       from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY LOG OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MSRSAVE" "1" "December 2016" "" ""
.
.SH "NAME"
\fBmsrsave\fR \- msr\-safe save restore application
.
.SH "SYNOPSIS"
.
.TP
\fBSAVE MSR:\fR
\fBmsrsave\fR outfile
.
.TP
\fBRESTORE MSR:\fR
\fBmsrsave\fR \fB\-r\fR infile
.
.TP
\fBPRINT VERSION OR HELP:\fR
\fBmsrsave \-\-version\fR | \fB\-\-help\fR
.
.SH "DESCRIPTION"
The \fBmsrsave\fR application is used save to a file the state of all
MSR values that the current MSR whitelist enables to be written or
restore the MSR values from a saved state file\. The msrsave
application also respects the standard \fB\-\-version\fR and
\fB\-\-help\fR options for printing the msr\-safe package version or a
brief message about usage\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-help\fR
.
.br
Print brief summary of the command line usage information, then exit\.
.
.TP
\fB\-\-version\fR
.
.br
Print version of msr\-safe package to standard output, then exit\.
.
.TP
\fB\-r\fR
.
.br
Restore the MSR values that are recorded in an existing MSR save state
file\.
.
.SH "COPYRIGHT"
Copyright (C) 2016, Intel Corporation\. All rights reserved\.
